### ISSUE TITLE
error when i am going launch stable diffusion after install moviepy

### ISSUE THREAD

**Issue by UnaiGar** [yownas/seed_travel#15]
I installed mviepy, and when I launch stable diffusion I get the following error:

venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: d15c125db7f9c153aaf613ad5c3522d0142a36b2
Installing requirements for Web UI
Launching Web UI with arguments:
Error loading script: get-latest-imagemagick-win.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 71, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\scripts\get-latest-imagemagick-win.py", line 9, in <module>
    content = urlopen(BINARIES_URL).read().decode("utf-8")
  File "C:\Program Files\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [7460a6fa] from C:\stable-diffusion-webui\models\Stable-diffusion\model.ckpt
Global Step: 470000
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

Do you know why?

Thanks.

**Comment by yownas** [comment]
This seem to be caused by another script.
`
File "C:\stable-diffusion-webui\scripts\get-latest-imagemagick-win.py", line 9`

It is nothing I recognize and it is not part of the seed_travel script, don't think I can offer much help, sorry.
