### ISSUE TITLE
 'StableDiffusionProcessingTxt2Img' object has no attribute 'sampler_index'

### ISSUE THREAD

**Issue by paduel** [yownas/seed_travel#24]
I follow your instructions, but I get this error:

```
Traceback (most recent call last):
  File "C:\Users\padi\sd_webui\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\padi\sd_webui\stable-diffusion-webui\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "C:\Users\padi\sd_webui\stable-diffusion-webui\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\padi\sd_webui\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "C:\Users\padi\sd_webui\stable-diffusion-webui\extensions\seed_travel\scripts\seed_travel.py", line 66, in run
    if not allowdefsampler and p.sampler_index == 0:
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'sampler_index'
```

Thank you for your help.

**Comment by yownas** [comment]
Hm. Seems like ATUOMATIC1111 changed how samplers are presented. A quick workaround is to check the "Allow the default Euler a Sampling method"-checkbox. I'll take a look at this as soon as I get home from work.

**Comment by paduel** [comment]
The workaround worked for me. Thanks for the quick response and for this great code.

I hope you can fix it easily.

**Comment by yownas** [comment]
It was an easy fix, just had to change "p.sampler_index = 0" to "p.sampler_name = 'Euler a'". :)

Thank you for alerting me to this, could have taken a while to notice it myself.
