### ISSUE TITLE
logger error :(

### ISSUE THREAD

**Issue by jvoxel** [yownas/seed_travel#27]
, 'None', 'None', 20, 2, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 1024, 576, True, 0.7, 256, 512, 5, False, False, False, False, '', 1, '', 0, '', True, False, False, '<br>Confused/new? View <a style="border-bottom: 1px #00ffff dotted;" href="https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script">the README</a> for usage instructions.<br><br>', False, True, False, True, '', '🔄', True, 4.0, '54,-1,777', 10.0, False, False, True, 30.0, True, False, False, 0, 20.0, 'linear', '30', 'grad_min', 0.01, 1, 'clip', 1.0, 1.0, 'mp4', 10.0, 0, 1, False, True) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 328, in run
    processed = script.run(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/seed_travel/scripts/seed_travel.py", line 178, in run
    clip.write_videofile(os.path.join(travel_path, f"travel-{travel_number:05}.mp4"), verbose=False, logger=None)
TypeError: write_videofile() got an unexpected keyword argument 'logger'

**Comment by yownas** [comment]
I wonder if you have the wrong version of moviepy installed (maybe brought in from another extension). This script uses an older version (1.0.3). Or if it could be a problem when running it in colab? (I never tried that.)

**Comment by jvoxel** [comment]
Thank you, now I have an Idea what to look for and yes I am running in a
colab. I will try checking what version of that dependency is installed and
I will report back to you, next time I run it.

**Comment by screan** [comment]
just installed and got the same error

````
TypeError: VideoClip.write_videofile() got an unexpected keyword argument 'logger'

````

**Comment by yownas** [comment]
I think I figured out what goes wrong. When you start a fresh Colab it (sometimes?) has moviepy 0.2.3.5 installed by default, which in turn make my install-script skip installing the correct version. I'll see if I can improve this check.

A quick workaround should be to add this line to the colab code. (at the top is fine)

`!pip install moviepy==1.0.3`

**Comment by ryango** [comment]
removing the logger param in write_videofile worked for me

**Comment by vladmandic** [comment]
its not wrong version of `moviepy`, its just that latest version of `moviepy` is obsolete (abandoned?) so if libraries it internally requires get upgraded by some other package, you end up with a mess. see #43.

**Comment by yownas** [comment]
Removed moviepy ffe0553c59e91067ebf1e4fc7ad85ca9c870bf57
