### ISSUE TITLE
Sizes of tensors must match except in dimension 1

### ISSUE THREAD

**Issue by olegchomp** [yownas/seed_travel#50]
I've got this error when trying to run script via API with RIFE enabled. If run without rife, everything works.

```
RIFE pass 2
Interpolating 4 images
API error: POST: http://127.0.0.1:7860/sdapi/v1/txt2img {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': 'Sizes of tensors must match except in dimension 1. Expected size 512 but got size 0 for tensor number 1 in the list.'}
```

**Comment by olegchomp** [comment]
full traceback:

```
Traceback (most recent call last):
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\SD\stable-diffusion-webui\modules\api\api.py", line 145, in exception_handling
    return await call_next(request)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "H:\SD\stable-diffusion-webui\modules\api\api.py", line 110, in log_and_time
    res: Response = await call_next(req)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\SD\stable-diffusion-webui\modules\api\api.py", line 314, in text2imgapi
    processed = scripts.scripts_txt2img.run(p, *p.script_args) # Need to pass args as list here
  File "H:\SD\stable-diffusion-webui\modules\scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "H:\SD\stable-diffusion-webui\extensions\seed_travel\scripts\seed_travel.py", line 442, in run
    output = execute(I0, I1, 1)
  File "H:\SD\stable-diffusion-webui\extensions\seed_travel\scripts\seed_travel.py", line 403, in execute
    res.append(rifemodel.inference(I0, I1, (i+1) * 1. / (n+1), scale))
  File "H:\SD\stable-diffusion-webui\extensions\seed_travel\scripts\rife\RIFE_HDv3.py", line 59, in inference
    imgs = torch.cat((img0, img1), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 512 but got size 0 for tensor number 1 in the list.
```

**Comment by yownas** [comment]
I tried to reproduce the error, but it didn't fail for me. Did it manage to generate any "un-rifed" video?

I think I've had an error like that in the normal webui when I was messing around with upscaling and SSIM. Does it fail even if you do something simple as a 512x512 and just a couple of frames?

**Comment by olegchomp** [comment]
> I tried to reproduce the error, but it didn't fail for me. Did it manage to generate any "un-rifed" video?
> 
> I think I've had an error like that in the normal webui when I was messing around with upscaling and SSIM. Does it fail even if you do something simple as a 512x512 and just a couple of frames?

un-rifed videos generates ok
i use default settings and 512x512 resolution. When i enable any step of rife it drops error, frames generating in folder, but video doesn't.

Did you try run through API? Because in UI it works. but get those error when using script through API

**Comment by yownas** [comment]
Yes. Nothing advanced though. Just a simple curl. Never used the api before, but I think I got it right. 

curl -X 'POST' \
  'http://localhost:7860/sdapi/v1/txt2img' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "enable_hr": false,
  "denoising_strength": 0,
  "firstphase_width": 0,
  "firstphase_height": 0,
  "hr_scale": 2,
  "hr_upscaler": "string",
  "hr_second_pass_steps": 0,
  "hr_resize_x": 0,
  "hr_resize_y": 0,
  "prompt": "api cat",
  "styles": [
    ""
  ],
  "seed": -1,
  "subseed": -1,
  "subseed_strength": 0,
  "seed_resize_from_h": -1,
  "seed_resize_from_w": -1,
  "sampler_name": "DDIM",
  "batch_size": 1,
  "n_iter": 1,
  "steps": 20,
  "cfg_scale": 7,
  "width": 512,
  "height": 512,
  "restore_faces": false,
  "tiling": false,
  "do_not_save_samples": false,
  "do_not_save_grid": false,
  "negative_prompt": "string",
  "eta": 0,
  "s_churn": 0,
  "s_tmax": 0,
  "s_tmin": 0,
  "s_noise": 1,
  "override_settings": {},
  "override_settings_restore_afterwards": true,
  "send_images": true,
  "save_images": false,
  "alwayson_scripts": {},
  "script_args": [true, 2, "", 5, "None", 3, false, 10, true, false, false, 0, 0, "None", 1.0, false, 0.0, 0.0, 0.001, 75, 5, false, true],
  "script_name": "Seed travel"
}'

**Comment by olegchomp** [comment]
oh, upscale_ratio should be 1, even if method = 'None'
thank you!

**Comment by yownas** [comment]
Ok, I think you found a bug that I need to fix. :)

If the "Upscaler" is None, it shouldn't matter which  "Upscale ratio" you have. I think I've just haven't run into that problem since the webui always set it to 1 as default. (It also seem to work if you have "Drop original frames" enabled.)

I'll take a look at this when I get back home from work.
