### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by Pojectmaster01** [yownas/seed_travel#56]
yesterday it working to day its this: 

"TypeError: Script.run() missing 23 required positional arguments: 'rnd_seed', 'seed_count', 'dest_seed', 'steps', 'curve', 'curvestr', 'loopback', 'video_fps', 'show_images', 'compare_paths', 'allowdefsampler', 'bump_seed', 'lead_inout', 'upscale_meth', 'upscale_ratio', 'use_cache', 'ssim_diff', 'ssim_ccrop', 'substep_min', 'ssim_diff_min', 'rife_passes', 'rife_drop', and 'save_stats'"

**Comment by Pojectmaster01** [comment]
*** Error completing request
*** Arguments: ('task(18zjtmmn3bq4nvt)', 'masterpiece, best quality, highres, al1, demon horns, slit pupils, black wing, low wing, feathered wings, black plate armor, <lora:albedo_(overlord)_v10:0.7>, cowboy shot, bed, sitting, hands on own chest,', 'EasyNegative, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, (worst quality:1.2), low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, lowres graffiti, (low quality lowres simple background:1.1),', [], 20, 16, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 5, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 'x264', 'blend', 10, 0, 0, False, True, True, True, 'intermediate', 'animation', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000216CD208550>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000216CD072AD0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000216CD072140>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000216CD070460>, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Bilinear', False, 'Lerp', '', '', False, False, None, True, True, False, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, None, None, False, 50, True, 4.0, '', 30.0, 'Linear', 3, True, 12.0, True, False, False, 0, 0.0, 'Lanczos', 1, True, 0, 0, 0.001, 75, 0.0, False, True) {}
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "D:\AI\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "D:\AI\stable-diffusion-webui\modules\txt2img.py", line 54, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 456, in run
        processed = script.run(p, *script_args)
    TypeError: Script.run() missing 23 required positional arguments: 'rnd_seed', 'seed_count', 'dest_seed', 'steps', 'curve', 'curvestr', 'loopback', 'video_fps', 'show_images', 'compare_paths', 'allowdefsampler', 'bump_seed', 'lead_inout', 'upscale_meth', 'upscale_ratio', 'use_cache', 'ssim_diff', 'ssim_ccrop', 'substep_min', 'ssim_diff_min', 'rife_passes', 'rife_drop', and 'save_stats'

---


whole error code

**Comment by yownas** [comment]
Not sure if that error comes from seed_travel (which hasn't changed since Apr 27th). Have you added/removed any other extensions without reloading the page? That could cause something like that. Where the form in the browser no longer matches what the webui server expects.

**Comment by Pojectmaster01** [comment]
no, i finish yesterday make seed_travel  and to day morning i start app and get this error, I have my guess that maybe something webui update today was in 'modules' and maybe she corrupted something.... i have automatic webui update ;/ 

but no sure 100%
